# Generated by Django 2.2.24 on 2021-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='client_rfxs',
            field=models.ManyToManyField(to='client_rfxs.ClientRfx'),
        ),
    ]
