# Generated by Django 2.2.24 on 2021-07-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20210623_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='client_rfxs',
        ),
    ]
