# Generated by Django 2.2.24 on 2021-06-12 05:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Webhook Type')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=20, verbose_name='Webhook Token')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
            },
        ),
    ]
