# Generated by Django 2.2.24 on 2021-06-17 12:24

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20210616_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, verbose_name='Webhook Token'),
        ),
    ]
