# Generated by Django 2.2.24 on 2021-06-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRfx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_of_outsourcing', models.CharField(blank=True, max_length=255, verbose_name='Generation of Outsourcing')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Region')),
                ('lead_region', models.CharField(blank=True, max_length=255, verbose_name='Lead Region')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='ClientRfx Type')),
                ('contract_term', models.CharField(blank=True, max_length=255, verbose_name='Contract term')),
                ('submittal_phase', models.CharField(blank=True, max_length=255, verbose_name='Submittal phase')),
                ('commercial_model', models.CharField(blank=True, max_length=255, verbose_name='Commercial model')),
                ('total_square_footage', models.CharField(blank=True, max_length=255, verbose_name='Total Square Footage')),
                ('total_headcount', models.CharField(blank=True, max_length=255, verbose_name='Total Headcount')),
                ('competitors', models.CharField(blank=True, max_length=255, verbose_name='Competitors')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('note_created', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note Created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rfx', to='clients.Client')),
            ],
            options={
                'verbose_name': 'ClientRfx',
                'verbose_name_plural': 'ClientRfxs',
            },
        ),
        migrations.CreateModel(
            name='ClientRfxTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Role')),
                ('person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Person')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('client_rfx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='client_rfxs.ClientRfx')),
            ],
            options={
                'verbose_name': 'ClientRfxTeam',
                'verbose_name_plural': 'ClientRfxTeams',
            },
        ),
        migrations.CreateModel(
            name='ClientRfxSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('activity', models.CharField(blank=True, max_length=255, verbose_name='Activity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('isDueDate', models.BooleanField(default=False, verbose_name='Due Date')),
                ('client_rfx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='client_rfxs.ClientRfx')),
            ],
            options={
                'verbose_name': 'ClientRfxSchedule',
                'verbose_name_plural': 'ClientRfxSchedules',
            },
        ),
    ]
