# Generated by Django 2.2.24 on 2021-06-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_rfxs', '0002_auto_20210623_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrfxteam',
            name='client_rfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='client_rfxs.ClientRfx'),
        ),
    ]
