# Generated by Django 2.2.24 on 2021-06-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_rfxs', '0003_auto_20210623_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrfx',
            name='note_created',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Note Created'),
        ),
    ]
