# Generated by Django 2.2.24 on 2021-06-29 04:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_rfxs', '0004_clientrfx_note_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrfx',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Settings'),
        ),
    ]
