# Generated by Django 2.2.24 on 2021-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_rfxs', '0005_clientrfx_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrfx',
            name='next_milestone',
            field=models.CharField(blank=True, max_length=500, verbose_name='Next Milestone'),
        ),
    ]
