# Generated by Django 2.2.24 on 2021-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_rfxs', '0006_clientrfx_next_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrfx',
            name='next_milestone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Next Milestone'),
        ),
    ]
