# Generated by Django 2.2.24 on 2021-06-27 14:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210625_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='assumption',
            name='buildings',
        ),
        migrations.RemoveField(
            model_name='assumption',
            name='client_rfx',
        ),
        migrations.RemoveField(
            model_name='assumption',
            name='details',
        ),
        migrations.RemoveField(
            model_name='clientservice',
            name='product_catalog',
        ),
        migrations.RemoveField(
            model_name='servicebybuilding',
            name='delivery_model',
        ),
        migrations.AddField(
            model_name='assumption',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='assumption',
            name='source',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('CLIENT', 'Client source'), ('SUPPLIER', 'Supplier'), ('FORMULA', 'Formula')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='assumption',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assumption',
            name='value',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='inScope',
            field=models.BooleanField(default=False, verbose_name='In Scope'),
        ),
        migrations.AlterField(
            model_name='assumption',
            name='service_by_building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='services.ServiceByBuilding'),
        ),
        migrations.AlterField(
            model_name='servicebybuilding',
            name='baseline_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Baseline Cost'),
        ),
        migrations.AlterField(
            model_name='servicebybuilding',
            name='cost_per_sq_ft',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Cost per sq ft'),
        ),
        migrations.AlterField(
            model_name='servicebybuilding',
            name='year_1_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Year 1 Cost'),
        ),
        migrations.AlterField(
            model_name='servicebybuilding',
            name='year_2_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Year 2 Cost'),
        ),
        migrations.AlterField(
            model_name='servicebybuilding',
            name='year_3_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Year 3 Cost'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='deliveryModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_service', to='services.DeliveryModel'),
        ),
        migrations.AddField(
            model_name='servicebybuilding',
            name='deliveryModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_by_building', to='services.DeliveryModel'),
        ),
    ]
