# Generated by Django 2.2.24 on 2021-07-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210703_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebybuilding',
            name='inScope',
            field=models.BooleanField(default=True, verbose_name='In Scope'),
        ),
    ]
