# Generated by Django 2.2.24 on 2021-07-06 07:25

from django.db import migrations, models
from services.models import ServiceByBuilding


def reset_inScope_to_false(_, __):
    try:
        for service in ServiceByBuilding.objects.all():
            service.inScope = False
            service.save()
    except:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0007_servicebybuilding_inscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebybuilding',
            name='inScope',
            field=models.BooleanField(default=False, verbose_name='In Scope'),
        ),
        migrations.RunPython(reset_inScope_to_false, reverse_code=migrations.RunPython.noop)
    ]
