# Generated by Django 2.2.24 on 2021-07-07 19:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplier_client_rfxs'),
        ('services', '0008_auto_20210706_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebybuilding',
            name='currency',
            field=models.CharField(blank=True, max_length=20, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='servicebybuilding',
            name='pricing_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pricing Type'),
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Price')),
                ('service_by_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='services.ServiceByBuilding')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicebybuilding_prices', to='suppliers.Supplier')),
            ],
            options={
                'verbose_name': 'SupplierPrice',
                'verbose_name_plural': 'SupplierPrices',
            },
        ),
        migrations.CreateModel(
            name='JLLEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Estimate')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('service_by_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='services.ServiceByBuilding')),
            ],
            options={
                'verbose_name': 'JLLEstimate',
                'verbose_name_plural': 'JLLEstimates',
            },
        ),
    ]
