# Generated by Django 2.2.24 on 2021-06-25 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Log name')),
                ('detail', models.TextField(blank=True, verbose_name='Detail')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Meta Data')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
