# Generated by Django 2.2.24 on 2021-06-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(default='empty', max_length=255, verbose_name='Building Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='client_building_area_type',
            field=models.CharField(default='empty', max_length=255, verbose_name='Client Building Area Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='main_region',
            field=models.CharField(blank=True, choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('LATAM', 'LATAM'), ('NOAM', 'NOAM')], max_length=5, verbose_name='Main Region'),
        ),
        migrations.AddField(
            model_name='building',
            name='sub_region',
            field=models.CharField(blank=True, choices=[('ANZ', 'ANZ'), ('N_ASIA', 'North Asia'), ('ISA', 'ISA'), ('ASEAN', 'ASEAN'), ('S_ASIA', 'South Asia'), ('APAC', 'APAC'), ('EMEA', 'EMEA'), ('South', 'South'), ('MEA', 'MEA'), ('DACH', 'DACH'), ('CEE', 'CEE'), ('North', 'North'), ('UK_IE', 'UK & IE'), ('CAR', 'CAR'), ('GLA', 'GLA'), ('NLA', 'NLA'), ('SLA', 'SLA'), ('BRAZIL', 'Brazil'), ('MEXICO', 'Mexico'), ('NOAM', 'NOAM')], max_length=50, verbose_name='Sub Region'),
        ),
    ]
