# Generated by Django 2.2.24 on 2021-06-25 22:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20210625_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingfloorarea',
            name='building_floor',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='work_shifts',
            new_name='worker_shifts',
        ),
        migrations.RemoveField(
            model_name='building',
            name='calculated_headcount',
        ),
        migrations.RemoveField(
            model_name='building',
            name='client_building_area_type',
        ),
        migrations.RemoveField(
            model_name='building',
            name='client_building_type',
        ),
        migrations.RemoveField(
            model_name='building',
            name='days_and_hours_of_operation',
        ),
        migrations.RemoveField(
            model_name='building',
            name='is_in_scope_of_pursuit',
        ),
        migrations.RemoveField(
            model_name='building',
            name='metropolitan_area',
        ),
        migrations.RemoveField(
            model_name='building',
            name='metropolitan_tier',
        ),
        migrations.RemoveField(
            model_name='building',
            name='property_name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='building',
            name='building_area_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Client Building Area Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='days_operation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Days of Operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_sub_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Floor Sub-Area'),
        ),
        migrations.AddField(
            model_name='building',
            name='green_area_units',
            field=models.CharField(blank=True, max_length=50, verbose_name='Green Area Units'),
        ),
        migrations.AddField(
            model_name='building',
            name='gross_floor_area_units',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gross Floor Area Units'),
        ),
        migrations.AddField(
            model_name='building',
            name='hours_operation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Hours of Operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='scope_pursuit',
            field=models.CharField(default='N', max_length=1, verbose_name='IN SCOPE OF PURSUIT?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='client_rfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='client_rfxs.ClientRfx'),
        ),
        migrations.AlterField(
            model_name='building',
            name='client_site_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Client Site ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='green_area',
            field=models.IntegerField(default=0, verbose_name='Green Area'),
        ),
        migrations.AlterField(
            model_name='building',
            name='gross_floor_area',
            field=models.IntegerField(default=0, verbose_name='Gross Floor Area'),
        ),
        migrations.AlterField(
            model_name='building',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('Full Service Gross', 'Full Service Gross'), ('Modified Gross', 'Modified Gross'), ('Absolute Net', 'Absolute Net'), ('NetNetNet', 'NetNetNet')], max_length=20, verbose_name='Lease Type'),
        ),
        migrations.AlterField(
            model_name='building',
            name='main_region',
            field=models.CharField(blank=True, choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('LATAM', 'LATAM'), ('NOAM', 'NOAM')], max_length=50, verbose_name='Main Region'),
        ),
        migrations.AlterField(
            model_name='building',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Governing District'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='sub_region',
            field=models.CharField(blank=True, choices=[('ANZ', 'ANZ'), ('APAC', 'APAC'), ('ASEAN', 'ASEAN'), ('ISA', 'ISA'), ('N_ASIA', 'North Asia'), ('S_ASIA', 'South Asia'), ('CEE', 'CEE'), ('DACH', 'DACH'), ('EMEA', 'EMEA'), ('GLA', 'GLA'), ('MEXICO', 'Mexico'), ('NLA', 'NLA'), ('SLA', 'SLA'), ('APAC', 'APAC'), ('NOAM', 'NOAM')], max_length=50, verbose_name='Sub Region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='sub_region',
            field=models.CharField(blank=True, choices=[('ANZ', 'ANZ'), ('APAC', 'APAC'), ('ASEAN', 'ASEAN'), ('ISA', 'ISA'), ('N_ASIA', 'North Asia'), ('S_ASIA', 'South Asia'), ('CEE', 'CEE'), ('DACH', 'DACH'), ('EMEA', 'EMEA'), ('GLA', 'GLA'), ('MEXICO', 'Mexico'), ('NLA', 'NLA'), ('SLA', 'SLA'), ('APAC', 'APAC'), ('NOAM', 'NOAM')], max_length=50, verbose_name='Sub Region'),
        ),
        migrations.DeleteModel(
            name='BuildingFloor',
        ),
        migrations.DeleteModel(
            name='BuildingFloorArea',
        ),
    ]
