# Generated by Django 2.2.24 on 2021-06-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_auto_20210626_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='go_live_date',
            field=models.DateField(null=True, verbose_name='Go-Live Date'),
        ),
        migrations.AlterField(
            model_name='building',
            name='service_level',
            field=models.CharField(blank=True, choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=20, verbose_name='Service Level'),
        ),
    ]
