# Generated by Django 2.2.24 on 2021-06-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_auto_20210626_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='note_created',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Note Created'),
        ),
    ]
